id = "varlock-schema"
name = "Varlock Schema"
version = "0.1.3"
schema_version = 1
authors = ["dmno-dev", "petercr"]
description = "Varlock @env-spec language support for .env.schema files"
repository = "https://github.com/petercr/varlock-zed-extension"

[grammars.env]
repository = "https://github.com/petercr/varlock-zed-extension"
commit = "7659c2f0014abf8cfe8992b9c5e4ed25b98433d3"
path = "tree-sitter-varlock-schema"

[language_servers.varlock-schema-language-server]
language = "Varlock Schema"
name = "Varlock Schema LSP"
languages = ["Varlock Schema"]

[language_servers.varlock-schema-language-server.language_ids]
"Varlock Schema" = "env-spec"
