/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_schema_comment_marker = 2,
  anon_sym_AT = 3,
  anon_sym_EQ = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_COMMA = 7,
  aux_sym_decorator_name_token1 = 8,
  anon_sym_DOLLAR = 9,
  anon_sym_DOLLAR_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_COLON_DASH = 12,
  anon_sym_DOLLAR_LPAREN = 13,
  sym_shell_command = 14,
  sym_identifier = 15,
  anon_sym_true = 16,
  anon_sym_false = 17,
  sym_integer = 18,
  anon_sym_DQUOTE = 19,
  aux_sym__interpolated_content_token1 = 20,
  anon_sym_SQUOTE = 21,
  aux_sym_string_literal_token1 = 22,
  sym_escape_sequence = 23,
  sym_url = 24,
  sym_regex_literal = 25,
  sym_raw_value = 26,
  sym_source_file = 27,
  sym_schema_comment = 28,
  sym_decorator = 29,
  sym_decorator_call = 30,
  sym_decorator_arguments = 31,
  sym_decorator_argument = 32,
  sym_decorator_option = 33,
  sym_decorator_value = 34,
  sym_resolver_call = 35,
  sym_decorator_name = 36,
  sym_decorator_option_name = 37,
  sym_decorator_identifier = 38,
  sym_resolver_name = 39,
  sym_variable = 40,
  sym_interpolated_variable = 41,
  sym_value = 42,
  sym_bool = 43,
  sym_string_interpolated = 44,
  sym__interpolated_content = 45,
  sym_string_literal = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_schema_comment_repeat1 = 48,
  aux_sym_decorator_arguments_repeat1 = 49,
  aux_sym_string_interpolated_repeat1 = 50,
  aux_sym_string_literal_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_schema_comment_marker] = "schema_comment_marker",
  [anon_sym_AT] = "@",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [aux_sym_decorator_name_token1] = "decorator_name_token1",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON_DASH] = ":-",
  [anon_sym_DOLLAR_LPAREN] = "$(",
  [sym_shell_command] = "shell_command",
  [sym_identifier] = "identifier",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_integer] = "integer",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__interpolated_content_token1] = "_interpolated_content_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_url] = "url",
  [sym_regex_literal] = "regex_literal",
  [sym_raw_value] = "raw_value",
  [sym_source_file] = "source_file",
  [sym_schema_comment] = "schema_comment",
  [sym_decorator] = "decorator",
  [sym_decorator_call] = "decorator_call",
  [sym_decorator_arguments] = "decorator_arguments",
  [sym_decorator_argument] = "decorator_argument",
  [sym_decorator_option] = "decorator_option",
  [sym_decorator_value] = "decorator_value",
  [sym_resolver_call] = "resolver_call",
  [sym_decorator_name] = "decorator_name",
  [sym_decorator_option_name] = "decorator_option_name",
  [sym_decorator_identifier] = "decorator_identifier",
  [sym_resolver_name] = "resolver_name",
  [sym_variable] = "variable",
  [sym_interpolated_variable] = "interpolated_variable",
  [sym_value] = "value",
  [sym_bool] = "bool",
  [sym_string_interpolated] = "string_interpolated",
  [sym__interpolated_content] = "_interpolated_content",
  [sym_string_literal] = "string_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_schema_comment_repeat1] = "schema_comment_repeat1",
  [aux_sym_decorator_arguments_repeat1] = "decorator_arguments_repeat1",
  [aux_sym_string_interpolated_repeat1] = "string_interpolated_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_schema_comment_marker] = sym_schema_comment_marker,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_decorator_name_token1] = aux_sym_decorator_name_token1,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON_DASH] = anon_sym_COLON_DASH,
  [anon_sym_DOLLAR_LPAREN] = anon_sym_DOLLAR_LPAREN,
  [sym_shell_command] = sym_shell_command,
  [sym_identifier] = sym_identifier,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_integer] = sym_integer,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__interpolated_content_token1] = aux_sym__interpolated_content_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_url] = sym_url,
  [sym_regex_literal] = sym_regex_literal,
  [sym_raw_value] = sym_raw_value,
  [sym_source_file] = sym_source_file,
  [sym_schema_comment] = sym_schema_comment,
  [sym_decorator] = sym_decorator,
  [sym_decorator_call] = sym_decorator_call,
  [sym_decorator_arguments] = sym_decorator_arguments,
  [sym_decorator_argument] = sym_decorator_argument,
  [sym_decorator_option] = sym_decorator_option,
  [sym_decorator_value] = sym_decorator_value,
  [sym_resolver_call] = sym_resolver_call,
  [sym_decorator_name] = sym_decorator_name,
  [sym_decorator_option_name] = sym_decorator_option_name,
  [sym_decorator_identifier] = sym_decorator_identifier,
  [sym_resolver_name] = sym_resolver_name,
  [sym_variable] = sym_variable,
  [sym_interpolated_variable] = sym_interpolated_variable,
  [sym_value] = sym_value,
  [sym_bool] = sym_bool,
  [sym_string_interpolated] = sym_string_interpolated,
  [sym__interpolated_content] = sym__interpolated_content,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_schema_comment_repeat1] = aux_sym_schema_comment_repeat1,
  [aux_sym_decorator_arguments_repeat1] = aux_sym_decorator_arguments_repeat1,
  [aux_sym_string_interpolated_repeat1] = aux_sym_string_interpolated_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_schema_comment_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_decorator_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_shell_command] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__interpolated_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_regex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_value] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_schema_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_call] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_option] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_value] = {
    .visible = true,
    .named = true,
  },
  [sym_resolver_call] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_name] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_option_name] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_resolver_name] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolated_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_string_interpolated] = {
    .visible = true,
    .named = true,
  },
  [sym__interpolated_content] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_schema_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decorator_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_interpolated_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 0},
    {field_value, 2},
  [4] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 9,
  [13] = 10,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 20,
  [38] = 21,
  [39] = 22,
  [40] = 40,
  [41] = 32,
  [42] = 42,
  [43] = 31,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 23,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 28,
  [57] = 25,
  [58] = 30,
  [59] = 34,
  [60] = 60,
  [61] = 26,
  [62] = 44,
  [63] = 33,
  [64] = 53,
  [65] = 20,
  [66] = 21,
  [67] = 22,
  [68] = 24,
  [69] = 53,
  [70] = 70,
  [71] = 71,
  [72] = 70,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 76,
  [84] = 70,
  [85] = 77,
  [86] = 81,
  [87] = 81,
  [88] = 77,
  [89] = 79,
  [90] = 80,
  [91] = 71,
  [92] = 82,
  [93] = 79,
  [94] = 80,
  [95] = 82,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '"', 62,
        '#', 28,
        '$', 48,
        '\'', 66,
        '(', 31,
        ')', 32,
        ',', 33,
        '/', 8,
        ':', 7,
        '=', 30,
        '@', 29,
        '\\', 12,
        '_', 56,
        'f', 37,
        'h', 45,
        't', 42,
        '}', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(62);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == 'f') ADVANCE(84);
      if (lookahead == 'h') ADVANCE(92);
      if (lookahead == 't') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(62);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '$') ADVANCE(48);
      if (lookahead == '\\') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(56);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(55);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(51);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(78);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '@') ADVANCE(27);
      END_STATE();
    case 12:
      ADVANCE_MAP(
        '"', 70,
        '$', 70,
        '\'', 70,
        '\\', 70,
        'b', 70,
        'f', 70,
        'n', 70,
        'r', 70,
        't', 70,
      );
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 14:
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 16:
      if (eof) ADVANCE(19);
      if (lookahead == '\n') SKIP(16);
      if (lookahead == '"') ADVANCE(62);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == 'f') ADVANCE(84);
      if (lookahead == 'h') ADVANCE(92);
      if (lookahead == 't') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '"', 62,
        '#', 20,
        '$', 48,
        '\'', 66,
        '(', 31,
        ')', 32,
        ',', 33,
        '/', 8,
        ':', 7,
        '=', 30,
        '@', 29,
        'f', 37,
        't', 42,
        '}', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == '@') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(56);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '@') ADVANCE(27);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead == '"' ||
          lookahead == '$' ||
          lookahead == '\\') ADVANCE(27);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == '@') ADVANCE(65);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead == '\'' ||
          lookahead == '\\') ADVANCE(27);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == '@') ADVANCE(69);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead == '$' ||
          lookahead == '(' ||
          lookahead == ')') ADVANCE(27);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == '@') ADVANCE(55);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(65);
      if (lookahead == '"' ||
          lookahead == '$' ||
          lookahead == '\\') ADVANCE(27);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(69);
      if (lookahead == '\'' ||
          lookahead == '\\') ADVANCE(27);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(55);
      if (lookahead == '$' ||
          lookahead == '(' ||
          lookahead == ')') ADVANCE(27);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_schema_comment_marker);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '@') ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == '-') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == 's') ADVANCE(36);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 'a') ADVANCE(40);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 'e') ADVANCE(58);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 'e') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 'l') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 'p') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 'r') ADVANCE(46);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 's') ADVANCE(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 't') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 't') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == 'u') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_decorator_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '(') ADVANCE(52);
      if (lookahead == '{') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COLON_DASH);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_shell_command);
      if (lookahead == '#') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_shell_command);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead == '$' ||
          lookahead == '(' ||
          lookahead == ')') ADVANCE(27);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == '@') ADVANCE(55);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_shell_command);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym__interpolated_content_token1);
      if (lookahead == '#') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead) &&
          lookahead != '\\') ADVANCE(65);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym__interpolated_content_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead == '"' ||
          lookahead == '$' ||
          lookahead == '\\') ADVANCE(27);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == '@') ADVANCE(65);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym__interpolated_content_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead == '\'' ||
          lookahead == '\\') ADVANCE(27);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == '@') ADVANCE(69);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_url);
      if (lookahead == '#') ADVANCE(77);
      if (lookahead == '/') ADVANCE(76);
      if (lookahead == ':') ADVANCE(13);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_url);
      if (lookahead == '#') ADVANCE(77);
      if (lookahead == '/') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_url);
      if (lookahead == '#') ADVANCE(77);
      if (lookahead == '/') ADVANCE(75);
      if (lookahead == ':') ADVANCE(94);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_url);
      if (lookahead == '#') ADVANCE(77);
      if (lookahead == '/') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_url);
      if (lookahead == '#') ADVANCE(77);
      if (lookahead == '=') ADVANCE(76);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_url);
      if (lookahead == '#') ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_regex_literal);
      if (lookahead == 'd' ||
          lookahead == 'g' ||
          lookahead == 'i' ||
          lookahead == 'm' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'v' ||
          lookahead == 'y') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(62);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == 'f') ADVANCE(84);
      if (lookahead == 'h') ADVANCE(92);
      if (lookahead == 't') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == '/') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == '/') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == ':') ADVANCE(81);
      if (lookahead == 's') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == ':') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 'a') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 'l') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 'p') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 'r') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 's') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 't') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 't') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 'u') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_raw_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(96);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 17},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 18},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 18},
  [29] = {.lex_state = 18},
  [30] = {.lex_state = 18},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 18},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 18},
  [36] = {.lex_state = 18},
  [37] = {.lex_state = 18},
  [38] = {.lex_state = 18},
  [39] = {.lex_state = 18},
  [40] = {.lex_state = 17},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 18},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 18},
  [45] = {.lex_state = 17},
  [46] = {.lex_state = 17},
  [47] = {.lex_state = 17},
  [48] = {.lex_state = 17},
  [49] = {.lex_state = 18},
  [50] = {.lex_state = 17},
  [51] = {.lex_state = 18},
  [52] = {.lex_state = 17},
  [53] = {.lex_state = 17},
  [54] = {.lex_state = 17},
  [55] = {.lex_state = 17},
  [56] = {.lex_state = 17},
  [57] = {.lex_state = 17},
  [58] = {.lex_state = 17},
  [59] = {.lex_state = 17},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 17},
  [62] = {.lex_state = 17},
  [63] = {.lex_state = 17},
  [64] = {.lex_state = 17},
  [65] = {.lex_state = 17},
  [66] = {.lex_state = 17},
  [67] = {.lex_state = 17},
  [68] = {.lex_state = 17},
  [69] = {.lex_state = 17},
  [70] = {.lex_state = 17},
  [71] = {.lex_state = 17},
  [72] = {.lex_state = 17},
  [73] = {.lex_state = 17},
  [74] = {.lex_state = 17},
  [75] = {.lex_state = 17},
  [76] = {.lex_state = 17},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 17},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 17},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 17},
  [84] = {.lex_state = 17},
  [85] = {.lex_state = 4},
  [86] = {.lex_state = 17},
  [87] = {.lex_state = 17},
  [88] = {.lex_state = 4},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 6},
  [91] = {.lex_state = 17},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 6},
  [95] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_schema_comment_marker] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_decorator_name_token1] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON_DASH] = ACTIONS(1),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_url] = ACTIONS(1),
    [sym_regex_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(78),
    [sym_schema_comment] = STATE(15),
    [sym_variable] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_schema_comment_marker] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(17), 1,
      aux_sym_decorator_name_token1,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(46), 1,
      sym_decorator_argument,
    STATE(73), 1,
      sym_decorator_arguments,
    STATE(74), 1,
      sym_decorator_option_name,
    STATE(91), 1,
      sym_resolver_name,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      sym_integer,
      sym_regex_literal,
    STATE(55), 2,
      sym_decorator_option,
      sym_decorator_value,
    STATE(59), 6,
      sym_resolver_call,
      sym_decorator_identifier,
      sym_interpolated_variable,
      sym_bool,
      sym_string_interpolated,
      sym_string_literal,
  [57] = 16,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(17), 1,
      aux_sym_decorator_name_token1,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_decorator_argument,
    STATE(74), 1,
      sym_decorator_option_name,
    STATE(76), 1,
      sym_decorator_arguments,
    STATE(91), 1,
      sym_resolver_name,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      sym_integer,
      sym_regex_literal,
    STATE(55), 2,
      sym_decorator_option,
      sym_decorator_value,
    STATE(59), 6,
      sym_resolver_call,
      sym_decorator_identifier,
      sym_interpolated_variable,
      sym_bool,
      sym_string_interpolated,
      sym_string_literal,
  [114] = 16,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(17), 1,
      aux_sym_decorator_name_token1,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_decorator_argument,
    STATE(74), 1,
      sym_decorator_option_name,
    STATE(83), 1,
      sym_decorator_arguments,
    STATE(91), 1,
      sym_resolver_name,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      sym_integer,
      sym_regex_literal,
    STATE(55), 2,
      sym_decorator_option,
      sym_decorator_value,
    STATE(59), 6,
      sym_resolver_call,
      sym_decorator_identifier,
      sym_interpolated_variable,
      sym_bool,
      sym_string_interpolated,
      sym_string_literal,
  [171] = 14,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(17), 1,
      aux_sym_decorator_name_token1,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(52), 1,
      sym_decorator_argument,
    STATE(74), 1,
      sym_decorator_option_name,
    STATE(91), 1,
      sym_resolver_name,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      sym_integer,
      sym_regex_literal,
    STATE(55), 2,
      sym_decorator_option,
      sym_decorator_value,
    STATE(59), 6,
      sym_resolver_call,
      sym_decorator_identifier,
      sym_interpolated_variable,
      sym_bool,
      sym_string_interpolated,
      sym_string_literal,
  [222] = 12,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(37), 1,
      aux_sym_decorator_name_token1,
    ACTIONS(39), 1,
      anon_sym_DOLLAR,
    ACTIONS(41), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(43), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    ACTIONS(51), 1,
      anon_sym_SQUOTE,
    STATE(35), 1,
      sym_decorator_value,
    STATE(71), 1,
      sym_resolver_name,
    ACTIONS(45), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(47), 2,
      sym_integer,
      sym_regex_literal,
    STATE(34), 6,
      sym_resolver_call,
      sym_decorator_identifier,
      sym_interpolated_variable,
      sym_bool,
      sym_string_interpolated,
      sym_string_literal,
  [266] = 12,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(53), 1,
      aux_sym_decorator_name_token1,
    STATE(54), 1,
      sym_decorator_value,
    STATE(91), 1,
      sym_resolver_name,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      sym_integer,
      sym_regex_literal,
    STATE(59), 6,
      sym_resolver_call,
      sym_decorator_identifier,
      sym_interpolated_variable,
      sym_bool,
      sym_string_interpolated,
      sym_string_literal,
  [310] = 8,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(49), 1,
      sym_value,
    ACTIONS(45), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(57), 3,
      sym_comment,
      sym_schema_comment_marker,
      sym_identifier,
    ACTIONS(59), 3,
      sym_integer,
      sym_url,
      sym_raw_value,
    STATE(51), 3,
      sym_bool,
      sym_string_interpolated,
      sym_string_literal,
  [342] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_DOLLAR,
    ACTIONS(67), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(69), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    ACTIONS(73), 2,
      aux_sym__interpolated_content_token1,
      sym_escape_sequence,
    STATE(10), 3,
      sym_interpolated_variable,
      sym__interpolated_content,
      aux_sym_string_interpolated_repeat1,
  [367] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_DOLLAR,
    ACTIONS(67), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(69), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 2,
      aux_sym__interpolated_content_token1,
      sym_escape_sequence,
    STATE(11), 3,
      sym_interpolated_variable,
      sym__interpolated_content,
      aux_sym_string_interpolated_repeat1,
  [392] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_DOLLAR,
    ACTIONS(82), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(85), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(88), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 2,
      aux_sym__interpolated_content_token1,
      sym_escape_sequence,
    STATE(11), 3,
      sym_interpolated_variable,
      sym__interpolated_content,
      aux_sym_string_interpolated_repeat1,
  [417] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_DOLLAR,
    ACTIONS(67), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(69), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(93), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 2,
      aux_sym__interpolated_content_token1,
      sym_escape_sequence,
    STATE(13), 3,
      sym_interpolated_variable,
      sym__interpolated_content,
      aux_sym_string_interpolated_repeat1,
  [442] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_DOLLAR,
    ACTIONS(67), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(69), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 2,
      aux_sym__interpolated_content_token1,
      sym_escape_sequence,
    STATE(11), 3,
      sym_interpolated_variable,
      sym__interpolated_content,
      aux_sym_string_interpolated_repeat1,
  [467] = 5,
    ACTIONS(103), 1,
      anon_sym_EQ,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    STATE(42), 1,
      sym_decorator_call,
    ACTIONS(101), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [486] = 5,
    ACTIONS(9), 1,
      sym_schema_comment_marker,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 1,
      sym_comment,
    STATE(16), 3,
      sym_schema_comment,
      sym_variable,
      aux_sym_source_file_repeat1,
  [504] = 5,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 1,
      sym_comment,
    ACTIONS(116), 1,
      sym_schema_comment_marker,
    ACTIONS(119), 1,
      sym_identifier,
    STATE(16), 3,
      sym_schema_comment,
      sym_variable,
      aux_sym_source_file_repeat1,
  [522] = 4,
    ACTIONS(126), 1,
      anon_sym_AT,
    ACTIONS(122), 2,
      ts_builtin_sym_end,
      sym_identifier,
    ACTIONS(124), 2,
      sym_comment,
      sym_schema_comment_marker,
    STATE(17), 2,
      sym_decorator,
      aux_sym_schema_comment_repeat1,
  [538] = 4,
    ACTIONS(133), 1,
      anon_sym_AT,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      sym_identifier,
    ACTIONS(131), 2,
      sym_comment,
      sym_schema_comment_marker,
    STATE(17), 2,
      sym_decorator,
      aux_sym_schema_comment_repeat1,
  [554] = 2,
    ACTIONS(137), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_EQ,
      anon_sym_LPAREN,
      sym_identifier,
  [566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 6,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DQUOTE,
      aux_sym__interpolated_content_token1,
      sym_escape_sequence,
  [578] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 6,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DQUOTE,
      aux_sym__interpolated_content_token1,
      sym_escape_sequence,
  [590] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 6,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DQUOTE,
      aux_sym__interpolated_content_token1,
      sym_escape_sequence,
  [602] = 3,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(145), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [615] = 2,
    ACTIONS(153), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [625] = 2,
    ACTIONS(157), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(155), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [635] = 2,
    ACTIONS(161), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(159), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [645] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_SQUOTE,
    STATE(27), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(165), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [659] = 2,
    ACTIONS(170), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(168), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [669] = 2,
    ACTIONS(174), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(172), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [679] = 2,
    ACTIONS(178), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(176), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [689] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_SQUOTE,
    STATE(27), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(182), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [703] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    STATE(31), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(186), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [717] = 2,
    ACTIONS(190), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(188), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [727] = 2,
    ACTIONS(194), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(192), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [737] = 2,
    ACTIONS(198), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(196), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [747] = 2,
    ACTIONS(202), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(200), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [757] = 2,
    ACTIONS(139), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(204), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [767] = 2,
    ACTIONS(141), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(206), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [777] = 2,
    ACTIONS(143), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(208), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [787] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      anon_sym_EQ,
    ACTIONS(145), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [801] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_SQUOTE,
    STATE(43), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(214), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [815] = 2,
    ACTIONS(218), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(216), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [825] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_SQUOTE,
    STATE(27), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(182), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [839] = 2,
    ACTIONS(224), 2,
      sym_comment,
      sym_schema_comment_marker,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_identifier,
  [849] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_decorator_arguments_repeat1,
  [862] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_decorator_arguments_repeat1,
  [875] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_decorator_arguments_repeat1,
  [888] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [899] = 2,
    ACTIONS(237), 2,
      ts_builtin_sym_end,
      sym_identifier,
    ACTIONS(239), 2,
      sym_comment,
      sym_schema_comment_marker,
  [908] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_AT,
    STATE(18), 2,
      sym_decorator,
      aux_sym_schema_comment_repeat1,
  [919] = 2,
    ACTIONS(241), 2,
      ts_builtin_sym_end,
      sym_identifier,
    ACTIONS(243), 2,
      sym_comment,
      sym_schema_comment_marker,
  [928] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(226), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [936] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
    ACTIONS(247), 1,
      anon_sym_COLON_DASH,
  [946] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(249), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [954] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(251), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [962] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [970] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(155), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [978] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(176), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [986] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(192), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [994] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(253), 1,
      aux_sym_decorator_name_token1,
    STATE(14), 1,
      sym_decorator_name,
  [1004] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(159), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1012] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(222), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1020] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1028] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    ACTIONS(257), 1,
      anon_sym_COLON_DASH,
  [1038] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(204), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1046] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(206), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1054] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(208), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1062] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1070] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
    ACTIONS(261), 1,
      anon_sym_COLON_DASH,
  [1080] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
  [1087] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_LPAREN,
  [1094] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
  [1101] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
  [1108] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_EQ,
  [1115] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_EQ,
  [1122] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
  [1129] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_identifier,
  [1136] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(279), 1,
      ts_builtin_sym_end,
  [1143] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identifier,
  [1150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_shell_command,
  [1157] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
  [1164] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_identifier,
  [1171] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
  [1178] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_RBRACE,
  [1185] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym_identifier,
  [1192] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
  [1199] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
  [1206] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(293), 1,
      sym_identifier,
  [1213] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(295), 1,
      sym_identifier,
  [1220] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym_shell_command,
  [1227] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_LPAREN,
  [1234] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(301), 1,
      sym_identifier,
  [1241] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_identifier,
  [1248] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      sym_shell_command,
  [1255] = 2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(307), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 57,
  [SMALL_STATE(4)] = 114,
  [SMALL_STATE(5)] = 171,
  [SMALL_STATE(6)] = 222,
  [SMALL_STATE(7)] = 266,
  [SMALL_STATE(8)] = 310,
  [SMALL_STATE(9)] = 342,
  [SMALL_STATE(10)] = 367,
  [SMALL_STATE(11)] = 392,
  [SMALL_STATE(12)] = 417,
  [SMALL_STATE(13)] = 442,
  [SMALL_STATE(14)] = 467,
  [SMALL_STATE(15)] = 486,
  [SMALL_STATE(16)] = 504,
  [SMALL_STATE(17)] = 522,
  [SMALL_STATE(18)] = 538,
  [SMALL_STATE(19)] = 554,
  [SMALL_STATE(20)] = 566,
  [SMALL_STATE(21)] = 578,
  [SMALL_STATE(22)] = 590,
  [SMALL_STATE(23)] = 602,
  [SMALL_STATE(24)] = 615,
  [SMALL_STATE(25)] = 625,
  [SMALL_STATE(26)] = 635,
  [SMALL_STATE(27)] = 645,
  [SMALL_STATE(28)] = 659,
  [SMALL_STATE(29)] = 669,
  [SMALL_STATE(30)] = 679,
  [SMALL_STATE(31)] = 689,
  [SMALL_STATE(32)] = 703,
  [SMALL_STATE(33)] = 717,
  [SMALL_STATE(34)] = 727,
  [SMALL_STATE(35)] = 737,
  [SMALL_STATE(36)] = 747,
  [SMALL_STATE(37)] = 757,
  [SMALL_STATE(38)] = 767,
  [SMALL_STATE(39)] = 777,
  [SMALL_STATE(40)] = 787,
  [SMALL_STATE(41)] = 801,
  [SMALL_STATE(42)] = 815,
  [SMALL_STATE(43)] = 825,
  [SMALL_STATE(44)] = 839,
  [SMALL_STATE(45)] = 849,
  [SMALL_STATE(46)] = 862,
  [SMALL_STATE(47)] = 875,
  [SMALL_STATE(48)] = 888,
  [SMALL_STATE(49)] = 899,
  [SMALL_STATE(50)] = 908,
  [SMALL_STATE(51)] = 919,
  [SMALL_STATE(52)] = 928,
  [SMALL_STATE(53)] = 936,
  [SMALL_STATE(54)] = 946,
  [SMALL_STATE(55)] = 954,
  [SMALL_STATE(56)] = 962,
  [SMALL_STATE(57)] = 970,
  [SMALL_STATE(58)] = 978,
  [SMALL_STATE(59)] = 986,
  [SMALL_STATE(60)] = 994,
  [SMALL_STATE(61)] = 1004,
  [SMALL_STATE(62)] = 1012,
  [SMALL_STATE(63)] = 1020,
  [SMALL_STATE(64)] = 1028,
  [SMALL_STATE(65)] = 1038,
  [SMALL_STATE(66)] = 1046,
  [SMALL_STATE(67)] = 1054,
  [SMALL_STATE(68)] = 1062,
  [SMALL_STATE(69)] = 1070,
  [SMALL_STATE(70)] = 1080,
  [SMALL_STATE(71)] = 1087,
  [SMALL_STATE(72)] = 1094,
  [SMALL_STATE(73)] = 1101,
  [SMALL_STATE(74)] = 1108,
  [SMALL_STATE(75)] = 1115,
  [SMALL_STATE(76)] = 1122,
  [SMALL_STATE(77)] = 1129,
  [SMALL_STATE(78)] = 1136,
  [SMALL_STATE(79)] = 1143,
  [SMALL_STATE(80)] = 1150,
  [SMALL_STATE(81)] = 1157,
  [SMALL_STATE(82)] = 1164,
  [SMALL_STATE(83)] = 1171,
  [SMALL_STATE(84)] = 1178,
  [SMALL_STATE(85)] = 1185,
  [SMALL_STATE(86)] = 1192,
  [SMALL_STATE(87)] = 1199,
  [SMALL_STATE(88)] = 1206,
  [SMALL_STATE(89)] = 1213,
  [SMALL_STATE(90)] = 1220,
  [SMALL_STATE(91)] = 1227,
  [SMALL_STATE(92)] = 1234,
  [SMALL_STATE(93)] = 1241,
  [SMALL_STATE(94)] = 1248,
  [SMALL_STATE(95)] = 1255,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, 0, 1),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_interpolated_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_interpolated_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_interpolated_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_interpolated_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_interpolated_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator, 2, 0, 2),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator, 2, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_schema_comment_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_schema_comment_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema_comment, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_schema_comment, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_name, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator_name, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_variable, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_variable, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_variable, 5, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_identifier, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator_identifier, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolver_name, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolver_call, 4, 0, 1),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_resolver_call, 4, 0, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_interpolated, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_interpolated, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_call, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator_call, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolver_call, 3, 0, 1),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_resolver_call, 3, 0, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_value, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator_value, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator, 4, 0, 4),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator, 4, 0, 4),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_call, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator_call, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_variable, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_variable, 3, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_variable, 5, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_option_name, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator, 3, 0, 2),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorator, 3, 0, 2),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_interpolated, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_interpolated, 3, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decorator_arguments_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_decorator_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_arguments, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_arguments, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 3),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 3),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_option, 3, 0, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_argument, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [279] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_env(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
